stages:
  - build
  - test
  - deploy

variables:
  BUILD_DIR: "build"
  CONFIGURATION: "Release"

before_script:
  - apt-get update && apt-get install -y cmake libgtest-dev build-essential
  - cd /usr/src/gtest
  - cmake .
  - make
  - cp *.a /usr/lib || echo "No .a files found, skipping"
  - cd $CI_PROJECT_DIR

build:
  stage: build
  script:
    - rm -rf $BUILD_DIR
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 1 hour

test:
  stage: test
  script:
    - cd $BUILD_DIR
    - ctest --output-on-failure  # runs tests defined in CMake (if using CTest)
  dependencies:
    - build
  artifacts:
    when: always
    reports:
      junit: $BUILD_DIR/test_results.xml  # if you generate junit xml from tests
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - echo "Deploying calculator..."
    - mkdir -p deploy_output
    - cp $BUILD_DIR/calculator deploy_output/ || echo "calculator binary not found"
    - cp $BUILD_DIR/test_calculator deploy_output/ || echo "test_calculator binary not found"
    - ls deploy_output
  dependencies:
    - build
  artifacts:
    paths:
      - deploy_output
    expire_in: 1 hour

