stages:
  - build
  - test

variables:
  BUILD_DIR: "build"
  CONFIGURATION: "Release"

before_script:
  - apt-get update && apt-get install -y cmake libgtest-dev build-essential
  # Build GoogleTest libraries (required because libgtest-dev only installs sources)
  - cd /usr/src/gtest
  - cmake .
  - make
  - cp *.a /usr/lib || echo "No .a files found, skipping"
  - cd $CI_PROJECT_DIR

build:
  stage: build
  script:
    - rm -rf $BUILD_DIR
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 1 hour

test:
  stage: test
  script:
    - cd $BUILD_DIR
    # Run test executable with GoogleTest XML output
    - ./test_calculator --gtest_output=xml:test_results.xml
  dependencies:
    - build
  artifacts:
    when: always
    reports:
      junit: $BUILD_DIR/test_results.xml
    paths:
      - $BUILD_DIR/test_results.xml
    expire_in: 1 hour
