version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bullseye
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y cmake libgtest-dev build-essential
            cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib || echo "skip"
      - run:
          name: Build project
          command: |
            rm -rf build
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build .

  test:
    docker:
      - image: circleci/buildpack-deps:bullseye
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd build
            ctest --output-on-failure

  deploy:
    docker:
      - image: circleci/buildpack-deps:bullseye
    steps:
      - checkout
      - run:
          name: Deploy binaries
          command: |
            mkdir -p deploy_output
            cp build/calculator deploy_output/ || echo "calculator not found"
            cp build/test_calculator deploy_output/ || echo "test_calculator not found"
            ls deploy_output

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
