version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/gcc:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libgtest-dev build-essential
            cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib || true
      - run:
          name: Build and Test
          command: |
            mkdir -p build
            cd build
            cmake ..
            cmake --build .
            ctest --output-on-failure

workflows:
  build_and_test:
    jobs:
      - build_and_test
