version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libgtest-dev build-essential
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp libgtest.a libgtest_main.a /usr/lib || echo "No .a files found, skipping"
      - run:
          name: Build project
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build .
            cp test_calculator ../    # Copy test executable to project root
      - persist_to_workspace:
          root: .
          paths:
            - test_calculator
            - build

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            ls -l
            ./test_calculator --gtest_output=xml:test_calculator_results.xml
      - store_test_results:
          path: ./test_calculator_results.xml
      - store_artifacts:
          path: ./test_calculator_results.xml

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
