version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgtest-dev cmake build-essential
            cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib || echo "skip"
      - run:
          name: Build calculator
          command: |
            rm -rf build
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build .

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run calculator tests
          command: |
            cd build
            ctest --output-on-failure

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
