version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libgtest-dev build-essential
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp *.a /usr/lib || echo "No .a files found, skipping"
            cd $CIRCLE_WORKING_DIRECTORY
      - run:
          name: Build project
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            cmake --build .

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd build
            ./test_calculator --gtest_output=xml:test_results.xml
      - store_artifacts:
          path: build/test_results.xml
      - store_test_results:
          path: build/test_results.xml

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
